apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "adp-demo-01"
  description: "xvvv"
  annotations:
    github.com/project-slug: defra/adp-demo-01
spec:
  type: backend
  lifecycle: alpha
  owner: "group:default/adp-demo-01"
  system: system:default/fcp-demo-service
  